CREATE TABLE OBJECT_TYPE
(
	ObjectTypeId int PRIMARY KEY IDENTITY (1,1),
	ObjectType varchar(50) NOT NULL UNIQUE
)
GO

CREATE TABLE HIERARCHY_1
(
	Hierarchy1Id int PRIMARY KEY IDENTITY (1,1),
	Hierarchy1 varchar(50) NOT NULL UNIQUE
)
GO

CREATE TABLE HIERARCHY_2
(
	Hierarchy2Id int PRIMARY KEY IDENTITY (1,1),
	Hierarchy2 varchar(50) NOT NULL UNIQUE
)
GO

CREATE TABLE EAS_GROUP
(
	EasGroupId int PRIMARY KEY IDENTITY (1,1),
	EasGroup varchar(50) NOT NULL UNIQUE
)
GO

CREATE TABLE OTD
(
	OtdId int PRIMARY KEY IDENTITY (1,1),
	Otd varchar(50) NOT NULL UNIQUE
)
GO

CREATE TABLE TAG_OBJECT
(
	ObjectId int PRIMARY KEY IDENTITY (1,1),
	ObjectName varchar(50) NOT NULL UNIQUE,
	ObjectTypeId int NOT NULL FOREIGN KEY REFERENCES OBJECT_TYPE(ObjectTypeId),
)
GO
