
-- View
CREATE VIEW ObjectData

AS

	SELECT
		OBJECT.Id,
		OBJECT.SfiNumber,
		OBJECT.MainEqNumber,
		OBJECT.EqNumber,
		OBJECT.Description,
		VDU_GROUP.Name AS VduGroup,
		HIERARCHY_1.Name AS Hierarchy1,
		HIERARCHY_2.Name AS Hierarchy2,
		EAS_GROUP.Name AS EasGroup,
		ALARM_GROUP.Name AS AlarmGroup,
		OTD.Name AS Otd,
		OBJECT_TYPE.Name AS ObjectType,
		LOCATION_GROUP1.Name AS AcknowledgeAllowed,
		LOCATION_GROUP2.Name AS AlwaysVisible,
		NODE.Name AS Node,
		CABINET.Name AS Cabinet,
		OBJECT.Revision,
		OBJECT.LastModified
	FROM OBJECT
		LEFT JOIN VDU_GROUP ON OBJECT.VduGroupId = VDU_GROUP.Id
		LEFT JOIN HIERARCHY_1 ON OBJECT.Hierarchy1Id = HIERARCHY_1.Id
		LEFT JOIN HIERARCHY_2 ON OBJECT.Hierarchy2Id = HIERARCHY_2.Id
		LEFT JOIN EAS_GROUP ON OBJECT.EasGroupId = EAS_GROUP.Id
		LEFT JOIN ALARM_GROUP ON OBJECT.AlarmGroupId = ALARM_GROUP.Id
		LEFT JOIN OTD ON OBJECT.OtdId = OTD.Id
		LEFT JOIN OBJECT_TYPE ON OBJECT.ObjectTypeId = OBJECT_TYPE.Id
		LEFT JOIN LOCATION_GROUP AS LOCATION_GROUP1 ON OBJECT.AcknowledgeAllowedId = LOCATION_GROUP1.Id
		LEFT JOIN LOCATION_GROUP AS LOCATION_GROUP2 ON OBJECT.AlwaysVisibleId = LOCATION_GROUP2.Id
		LEFT JOIN NODE ON OBJECT.NodeId = NODE.Id
		LEFT JOIN CABINET ON OBJECT.CabinetId = CABINET.Id
