SET NOCOUNT ON


-- Insert sample data into SYMBOL
INSERT INTO SYMBOL (Name) SELECT 'FI' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name = 'FI')
INSERT INTO SYMBOL (Name) SELECT 'LAH' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='LAH')
INSERT INTO SYMBOL (Name) SELECT 'LAL' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='LAL')
INSERT INTO SYMBOL (Name) SELECT 'LI' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='LI')
INSERT INTO SYMBOL (Name) SELECT 'LIAL' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='LIAL')
INSERT INTO SYMBOL (Name) SELECT 'PAL' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='PAL')
INSERT INTO SYMBOL (Name) SELECT 'PI' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='PI')
INSERT INTO SYMBOL (Name) SELECT 'PIAL' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='PIAL')
INSERT INTO SYMBOL (Name) SELECT 'PTL' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='PTL')
INSERT INTO SYMBOL (Name) SELECT 'QI' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='QI')
INSERT INTO SYMBOL (Name) SELECT 'SAH' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='SAH')
INSERT INTO SYMBOL (Name) SELECT 'SI' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='SI')
INSERT INTO SYMBOL (Name) SELECT 'TI' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='TI')
INSERT INTO SYMBOL (Name) SELECT 'TIAH' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='TIAH')
INSERT INTO SYMBOL (Name) SELECT 'XA' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='XA')
INSERT INTO SYMBOL (Name) SELECT 'XC' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='XC')
INSERT INTO SYMBOL (Name) SELECT 'XI' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='XI')