CREATE TABLE [dbo].[OBJECT] (
    [Id]                   INT           PRIMARY KEY IDENTITY (1, 1) NOT NULL,
    [SfiNumber]            VARCHAR (50)  NOT NULL,
    [MainEqNumber]         VARCHAR (50)  NOT NULL,
    [EqNumber]             VARCHAR (50)  NULL,
    [Description]          VARCHAR (150) NOT NULL,
    [VduGroupId]           INT           NOT NULL,
    [Hierarchy1Id]         INT           NULL,
    [Hierarchy2Id]         INT           NULL,
    [EasGroupId]           INT           NULL,
    [AlarmGroupId]         INT           NULL,
    [OtdId]                INT           NULL,
    [ObjectTypeId]         INT           NULL,
    [AcknowledgeAllowedId] INT           NULL,
    [AlwaysVisibleId]      INT           NULL,
    [NodeId]               INT           NULL,
    [CabinetId]            INT           NOT NULL,
    [Revision]             VARCHAR (50)  NULL,
    [LastModified]         DATETIME      NULL,
    FOREIGN KEY ([AcknowledgeAllowedId]) REFERENCES [dbo].[LOCATION_GROUP] ([Id]),
    FOREIGN KEY ([AlarmGroupId]) REFERENCES [dbo].[ALARM_GROUP] ([Id]),
    FOREIGN KEY ([AlwaysVisibleId]) REFERENCES [dbo].[LOCATION_GROUP] ([Id]),
    FOREIGN KEY ([CabinetId]) REFERENCES [dbo].[CABINET] ([Id]),
    FOREIGN KEY ([EasGroupId]) REFERENCES [dbo].[EAS_GROUP] ([Id]),
    FOREIGN KEY ([Hierarchy1Id]) REFERENCES [dbo].[HIERARCHY_1] ([Id]),
    FOREIGN KEY ([Hierarchy2Id]) REFERENCES [dbo].[HIERARCHY_2] ([Id]),
    FOREIGN KEY ([NodeId]) REFERENCES [dbo].[NODE] ([Id]),
    FOREIGN KEY ([ObjectTypeId]) REFERENCES [dbo].[OBJECT_TYPE] ([Id]),
    FOREIGN KEY ([OtdId]) REFERENCES [dbo].[OTD] ([Id]),
    FOREIGN KEY ([VduGroupId]) REFERENCES [dbo].[VDU_GROUP] ([Id])
);

