CREATE TABLE [dbo].[TAG] (
    [Id]              INT           IDENTITY (1, 1) NOT NULL,
    [ObjectId]        INT           NULL,
    [ObjectTypeId]    INT           NULL,
    [EqSuffix]        VARCHAR (50)  NOT NULL,
    [Description]     VARCHAR (150) NOT NULL,
    [IoTypeId]        INT           NOT NULL,
    [SignalTypeId]    INT           NULL,
    [SymbolId]        INT           NULL,
    [EngUnitId]       INT           NULL,
    [AlarmDelay]      VARCHAR (50)  NULL,
    [RangeLow]        INT           NULL,
    [RangeHigh]       INT           NULL,
    [LowLowLimit]     INT           NULL,
    [LowLimit]        INT           NULL,
    [HighLimit]       INT           NULL,
    [HighHighLimit]   INT           NULL,
    [Slot]            INT           NULL,
    [Channel]         INT           NULL,
    [TP1]             INT           NULL,
    [TP2]             INT           NULL,
    [TP3]             INT           NULL,
    [TP4]             INT           NULL,
    [AbsoluteAddress] VARCHAR (50)  NULL,
    [SWPath]          VARCHAR (150) NULL,
    [DBName]          VARCHAR (150) NULL,
    [ModbusAddress]   INT           NULL,
    [ModbusBit]       INT           NULL,
    [IsE0]            BIT           NULL,
    [IsVDR]           BIT           NULL,
    [IOStatus]        VARCHAR (100) NULL,
    [LastModified]    DATETIME      NULL,
    [InterfaceModule] VARCHAR (50)  NULL,
    [UserLock]        BIT           NULL,
    [IOLock]          BIT           NULL,
    [BeijerBoxId]     INT           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([EngUnitId]) REFERENCES [dbo].[ENG_UNIT] ([Id]),
    FOREIGN KEY ([IoTypeId]) REFERENCES [dbo].[IO_TYPE] ([Id]),
    FOREIGN KEY ([ObjectId]) REFERENCES [dbo].[OBJECT] ([Id]),
    FOREIGN KEY ([ObjectTypeId]) REFERENCES [dbo].[OBJECT_TYPE] ([Id]),
    FOREIGN KEY ([SignalTypeId]) REFERENCES [dbo].[SIGNAL_TYPE] ([Id]),
    FOREIGN KEY ([SymbolId]) REFERENCES [dbo].[SYMBOL] ([Id])
);

