/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

SET NOCOUNT ON


-- Insert sample data into IO_TYPE
INSERT INTO IO_TYPE (Name) SELECT 'DI' WHERE NOT EXISTS (SELECT 1 FROM IO_TYPE WHERE Name = 'DI')
INSERT INTO IO_TYPE (Name) SELECT 'DO' WHERE NOT EXISTS (SELECT 1 FROM IO_TYPE WHERE Name = 'DO')
INSERT INTO IO_TYPE (Name) SELECT 'AI' WHERE NOT EXISTS (SELECT 1 FROM IO_TYPE WHERE Name = 'AI')
INSERT INTO IO_TYPE (Name) SELECT 'AO' WHERE NOT EXISTS (SELECT 1 FROM IO_TYPE WHERE Name = 'AO')
INSERT INTO IO_TYPE (Name) SELECT 'SDI' WHERE NOT EXISTS (SELECT 1 FROM IO_TYPE WHERE Name = 'SDI')
INSERT INTO IO_TYPE (Name) SELECT 'SDO' WHERE NOT EXISTS (SELECT 1 FROM IO_TYPE WHERE Name = 'SDO')
INSERT INTO IO_TYPE (Name) SELECT 'SAI' WHERE NOT EXISTS (SELECT 1 FROM IO_TYPE WHERE Name = 'SAI')
INSERT INTO IO_TYPE (Name) SELECT 'SAO' WHERE NOT EXISTS (SELECT 1 FROM IO_TYPE WHERE Name = 'SAO')

-- Insert sample data into SIGNAL_TYPE
INSERT INTO SIGNAL_TYPE (Name) SELECT 'NC' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'NC')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'NO' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'NO')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'NC, 230V Relay' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'NC, 230V Relay')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'NO, 230V Relay' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'NO, 230V Relay')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'Int' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'Int')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'Real' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'Real')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'Float' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'Float')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'Word' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'Word')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'Double' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'Double')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'U_B_AnalogValueLong' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'U_B_AnalogValueLong')
INSERT INTO SIGNAL_TYPE (Name) SELECT '4-20mA, 2W' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = '4-20mA, 2W')
INSERT INTO SIGNAL_TYPE (Name) SELECT '4-20mA, 3W' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = '4-20mA, 3W')
INSERT INTO SIGNAL_TYPE (Name) SELECT '4-20mA, 4W' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = '4-20mA, 4W')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'PT100, 3W' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'PT100, 3W')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'PT100, 4W' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'PT100, 4W')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'TC' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'TC')
INSERT INTO SIGNAL_TYPE (Name) SELECT '0-10V' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = '0-10V')

-- Insert connections into IO_SIGNAL_TYPE
-- DI
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'DI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'DI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'));

-- DO
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'DO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'DO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC, 230V Relay'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'DO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC, 230V Relay'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO, 230V Relay'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'DO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO, 230V Relay'));

-- SDI
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SDI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SDI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SDI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SDI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'));

-- SDO
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SDO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SDO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SDO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SDO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'));

-- AI
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 2W'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'AI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 2W'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 4W'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'AI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 4W'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'PT100, 3W'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'AI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'PT100, 3W'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'PT100, 4W'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'AI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'PT100, 4W'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'TC'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'AI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'TC'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = '0-10V'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'AI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = '0-10V'));

--AO
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 2W'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'AO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 2W'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = '0-10V'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'AO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = '0-10V'));

-- SAI
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Int'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Int'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Real'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Real'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Float'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Float'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Word'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Word'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Double'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Double'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'U_B_AnalogValueLong'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'U_B_AnalogValueLong'));

-- SAO
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Int'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Int'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Real'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Real'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Float'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Float'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Word'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Word'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Double'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Double'));
