IF EXISTS (SELECT name
	FROM sysobjects
	WHERE name = 'GetTagObjectData'
	AND type = 'V')
DROP VIEW GetTagObjectData
GO

CREATE VIEW GetTagObjectData

AS

SELECT
TAG_OBJECT.ObjectId,
TAG_OBJECT.ObjectName,
OBJECT_TYPE.ObjectType,
HIERARCHY_1.Hierarchy1,
HIERARCHY_2.Hierarchy2,
EAS_GROUP.EasGroup,
OTD.Otd

FROM TAG_OBJECT
INNER JOIN OBJECT_TYPE ON TAG_OBJECT.ObjectTypeId = OBJECT_TYPE.ObjectTypeId
INNER JOIN HIERARCHY_1 ON TAG_OBJECT.Hierarchy1Id = HIERARCHY_1.Hierarchy1Id
INNER JOIN HIERARCHY_2 ON TAG_OBJECT.Hierarchy2Id = HIERARCHY_2.Hierarchy2Id
INNER JOIN EAS_GROUP ON TAG_OBJECT.EasGroupId = EAS_GROUP.EasGroupId
INNER JOIN OTD ON TAG_OBJECT.OtdId = OTD.OtdId

GO