-- Check if View exists and deletes it if yes
IF EXISTS (SELECT name
	FROM sysobjects
	WHERE name = 'ObjectData'
	AND type = 'V')
DROP VIEW ObjectData
GO

-- View
CREATE VIEW ObjectData

AS

SELECT
OBJECT.Id,
OBJECT.SfiNumber,
OBJECT.MainEqNumber,
OBJECT.EqNumber,
OBJECT.Description,
HIERARCHY_1.Name Hierarchy1Name,
HIERARCHY_2.Name Hierarchy2Name,
VDU_GROUP.Name VduGroupName,
ALARM_GROUP.Name AlarmGroupName,
OTD.Name OtdName,
ACKNOWLEDGE_ALLOWED.Name AcknowledgeAllowedName,
ALWAYS_VISIBLE.Name AlwaysVisibleName,
NODE.Name NodeName,
CABINET.Name CabinetName

FROM OBJECT
INNER JOIN HIERARCHY_1 ON OBJECT.Hierarchy1Id = HIERARCHY_1.Id
INNER JOIN HIERARCHY_2 ON OBJECT.Hierarchy2Id = HIERARCHY_2.Id
INNER JOIN VDU_GROUP ON OBJECT.VduGroupId = VDU_GROUP.Id
INNER JOIN ALARM_GROUP ON OBJECT.AlarmGroupId = ALARM_GROUP.Id
INNER JOIN OTD ON OBJECT.OtdId = OTD.Id
INNER JOIN ACKNOWLEDGE_ALLOWED 
ON OBJECT.AcknowledgeAllowedId = ACKNOWLEDGE_ALLOWED.Id
INNER JOIN ALWAYS_VISIBLE 
ON OBJECT.AlwaysVisibleId = ALWAYS_VISIBLE.Id
INNER JOIN NODE ON OBJECT.NodeId = NODE.Id
INNER JOIN CABINET ON OBJECT.CabinetId = CABINET.Id

GO