DROP TABLE IF EXISTS OBJECT_TAG;
DROP TABLE IF EXISTS OBJECT;
DROP TABLE IF EXISTS TAG;
DROP TABLE IF EXISTS HIERARCHY_2;
DROP TABLE IF EXISTS HIERARCHY_1;
DROP TABLE IF EXISTS VDU_GROUP; --EAS group = VDU group
DROP TABLE IF EXISTS ALARM_GROUP; -- alarm groups
DROP TABLE IF EXISTS OTD;
DROP TABLE IF EXISTS ACKNOWLEDGE_ALLOWED;
DROP TABLE IF EXISTS ALWAYS_VISIBLE;
DROP TABLE IF EXISTS NODE;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS CABINET;
DROP TABLE IF EXISTS DATA_BLOCK;
DROP TABLE IF EXISTS SIGNAL_TYPE;
DROP TABLE IF EXISTS IO_TYPE;
DROP TABLE IF EXISTS ENG_UNIT;


CREATE TABLE HIERARCHY_1
(
	Id int PRIMARY KEY IDENTITY (1,1),
	Name varchar(50) NOT NULL UNIQUE
)
GO

CREATE TABLE HIERARCHY_2
(
	Id int PRIMARY KEY IDENTITY (1,1),
	Name varchar(50) NOT NULL UNIQUE,
	Hierarchy1Id int NOT NULL FOREIGN KEY REFERENCES HIERARCHY_1(Id)
)
GO

CREATE TABLE VDU_GROUP
(
	Id int PRIMARY KEY IDENTITY (1,1),
	Name varchar(50) NOT NULL UNIQUE
)
GO

CREATE TABLE ALARM_GROUP
(
	Id int PRIMARY KEY IDENTITY (1,1),
	Name varchar(50) NOT NULL UNIQUE
)
GO

CREATE TABLE OTD
(
	Id int PRIMARY KEY IDENTITY (1,1),
	Name varchar(50) NOT NULL UNIQUE
)
GO

CREATE TABLE ACKNOWLEDGE_ALLOWED
(
	Id int PRIMARY KEY IDENTITY (1,1),
	Name varchar(200) NOT NULL UNIQUE,
)
GO

CREATE TABLE ALWAYS_VISIBLE
(
	Id int PRIMARY KEY IDENTITY (1,1),
	Name varchar(200) NOT NULL UNIQUE,
)
GO

CREATE TABLE LOCATION
(
	Id int PRIMARY KEY IDENTITY (1,1),
	Name varchar(200) NOT NULL UNIQUE
)
GO

CREATE TABLE NODE
(
	Id int PRIMARY KEY IDENTITY (1,1),
	Name varchar(50) NOT NULL UNIQUE
)
GO

CREATE TABLE CABINET
(
	Id int PRIMARY KEY IDENTITY (1,1),
	Name varchar(50) NOT NULL UNIQUE
)
GO

CREATE TABLE IO_TYPE
(
	Id int PRIMARY KEY IDENTITY (1,1),
	Name varchar(50) NOT NULL UNIQUE
)
GO

CREATE TABLE SIGNAL_TYPE
(
	Id int PRIMARY KEY IDENTITY (1,1),
	Name varchar(50),
	IoTypeId int NOT NULL FOREIGN KEY REFERENCES IO_TYPE(Id)
)
GO

CREATE TABLE ENG_UNIT
(
	Id int PRIMARY KEY IDENTITY (1,1),
	Name varchar(50) UNIQUE,
	UnitId int UNIQUE
)
GO


CREATE TABLE OBJECT
(
	Id int PRIMARY KEY IDENTITY (1,1),
	SfiNumber int NOT NULL,
	MainEqNumber varchar(50) NOT NULL,
	EqNumber varchar(50),
	Description varchar(150) NOT NULL UNIQUE,
	Hierarchy1Id int NOT NULL FOREIGN KEY REFERENCES HIERARCHY_1(Id),
	Hierarchy2Id int NOT NULL FOREIGN KEY REFERENCES HIERARCHY_2(Id),
	VduGroupId int NOT NULL FOREIGN KEY REFERENCES VDU_GROUP(Id),
	AlarmGroupId int NOT NULL FOREIGN KEY REFERENCES ALARM_GROUP(Id),
	OtdId int NOT NULL FOREIGN KEY REFERENCES OTD(Id),
	AcknowledgeAllowedId int NOT NULL FOREIGN KEY REFERENCES ACKNOWLEDGE_ALLOWED(Id),
	AlwaysVisibleId int FOREIGN KEY REFERENCES ALWAYS_VISIBLE(Id),
	NodeId int NOT NULL FOREIGN KEY REFERENCES NODE(Id),
	CabinetId int NOT NULL FOREIGN KEY REFERENCES CABINET(Id),
)
GO

CREATE TABLE TAG
(
	Id int PRIMARY KEY IDENTITY (1,1),
	EqSuffix int NOT NULL,
	Description varchar(150) NOT NULL,
	IoTypeId int NOT NULL FOREIGN KEY REFERENCES IO_TYPE(Id),
	SignalTypeId int NOT NULL FOREIGN KEY REFERENCES SIGNAL_TYPE(Id),
	EngUnitId int FOREIGN KEY REFERENCES ENG_UNIT(Id),
	RangeLow int,
	RangeHigh int,
	LowLowLimit int,
	LowLimit int,
	HighLimit int,
	HighHighLimit int,
	Slot int,
	AbsoluteAddress varchar(50),
	SWPath varchar(150),
	DBName varchar(150),
	ModbusAddress int,
	ModbusBit int,
	IsE0 bit,
	IsVDR bit
)
GO

CREATE TABLE OBJECT_TAG
(
	Id int PRIMARY KEY IDENTITY (1,1),
	TagId int FOREIGN KEY REFERENCES TAG(Id),
	ObjectId int FOREIGN KEY REFERENCES OBJECT(Id),
)
