DROP TABLE IF EXISTS TAG_OBJECT;
DROP TABLE IF EXISTS OBJECT_TYPE;
DROP TABLE IF EXISTS HIERARCHY_1;
DROP TABLE IF EXISTS HIERARCHY_2;
DROP TABLE IF EXISTS EAS_GROUP;
DROP TABLE IF EXISTS OTD;

CREATE TABLE TAG_OBJECT
(
	ObjectId int PRIMARY KEY IDENTITY (1,1),
	ObjectName varchar(50) NOT NULL UNIQUE,
	ObjectTypeId int NOT NULL FOREIGN KEY REFERENCES OBJECT_TYPE(ObjectTypeId),
	Hierarchy1Id int NOT NULL FOREIGN KEY REFERENCES HIERARCHY_1(Hierarchy1Id),
	Hierarchy2Id int NOT NULL FOREIGN KEY REFERENCES HIERARCHY_2(Hierarchy2Id),
	EasGroupId int NOT NULL FOREIGN KEY REFERENCES EAS_GROUP(EasGroupId),
	OtdId int NOT NULL FOREIGN KEY REFERENCES EAS_GROUP(EasGroupId),
)
GO

CREATE TABLE OBJECT_TYPE
(
	ObjectTypeId int PRIMARY KEY IDENTITY (1,1),
	ObjectType varchar(50) NOT NULL UNIQUE
)
GO

CREATE TABLE HIERARCHY_1
(
	Hierarchy1Id int PRIMARY KEY IDENTITY (1,1),
	Hierarchy1 varchar(50) NOT NULL UNIQUE
)
GO

CREATE TABLE HIERARCHY_2
(
	Hierarchy2Id int PRIMARY KEY IDENTITY (1,1),
	Hierarchy2 varchar(50) NOT NULL UNIQUE,
	Hierarchy1Id int NOT NULL FOREIGN KEY REFERENCES HIERARCHY_1(Hierarchy1Id)
)
GO

CREATE TABLE EAS_GROUP
(
	EasGroupId int PRIMARY KEY IDENTITY (1,1),
	EasGroup varchar(50) NOT NULL UNIQUE
)
GO

CREATE TABLE OTD
(
	OtdId int PRIMARY KEY IDENTITY (1,1),
	Otd varchar(50) NOT NULL UNIQUE
)
GO