/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

SET NOCOUNT ON

-- Insert sample data into OTD
INSERT INTO OTD (Name) SELECT 'BO_1DI' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_1DI')
INSERT INTO OTD (Name) SELECT 'BO_8DI_8DO' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_8DI_8DO')
INSERT INTO OTD (Name) SELECT 'BO_Diag_Device' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_Diag_Device')
INSERT INTO OTD (Name) SELECT 'BO_Diag_Slot' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_Diag_Slot')
INSERT INTO OTD (Name) SELECT 'BO_Diag_HMI' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_Diag_HMI')
INSERT INTO OTD (Name) SELECT 'BO_AnalogIn' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_AnalogIn')
INSERT INTO OTD (Name) SELECT 'BO_AnalogIn_AllAlarms' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_AnalogIn_AllAlarms')
INSERT INTO OTD (Name) SELECT 'BO_AnalogOut' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_AnalogOut')
INSERT INTO OTD (Name) SELECT 'BO_Breaker' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_Breaker')
INSERT INTO OTD (Name) SELECT 'IASO_DeadMan' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'IASO_DeadMan')
INSERT INTO OTD (Name) SELECT 'BO_DutyStby' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_DutyStby')
INSERT INTO OTD (Name) SELECT 'BO_Motor' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_Motor')
INSERT INTO OTD (Name) SELECT 'BO_Motor2D2V' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_Motor2D2V')
INSERT INTO OTD (Name) SELECT 'BO_MotorFC' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_MotorFC')
INSERT INTO OTD (Name) SELECT 'BO_Precharge' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_Precharge')
INSERT INTO OTD (Name) SELECT 'BO_PID' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_PID')
INSERT INTO OTD (Name) SELECT 'BO_Valve' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_Valve')
INSERT INTO OTD (Name) SELECT 'BO_ValveAI_AO' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_ValveAI_AO')
INSERT INTO OTD (Name) SELECT 'BO_Value' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_Value')
INSERT INTO OTD (Name) SELECT 'BO_Tank' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_Tank')
INSERT INTO OTD (Name) SELECT 'BO_TwoSensors' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_TwoSensors')
INSERT INTO OTD (Name) SELECT 'BO_TwoSensors2' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_TwoSensors2')
INSERT INTO OTD (Name) SELECT 'BO_NetworkMonitor' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'BO_NetworkMonitor')
INSERT INTO OTD (Name) SELECT 'NA' WHERE NOT EXISTS (SELECT 1 FROM OTD WHERE Name = 'NA')

-- Insert sample data into IO_TYPE
INSERT INTO IO_TYPE (Name) SELECT 'DI' WHERE NOT EXISTS (SELECT 1 FROM IO_TYPE WHERE Name = 'DI')
INSERT INTO IO_TYPE (Name) SELECT 'DO' WHERE NOT EXISTS (SELECT 1 FROM IO_TYPE WHERE Name = 'DO')
INSERT INTO IO_TYPE (Name) SELECT 'AI' WHERE NOT EXISTS (SELECT 1 FROM IO_TYPE WHERE Name = 'AI')
INSERT INTO IO_TYPE (Name) SELECT 'AO' WHERE NOT EXISTS (SELECT 1 FROM IO_TYPE WHERE Name = 'AO')
INSERT INTO IO_TYPE (Name) SELECT 'SDI' WHERE NOT EXISTS (SELECT 1 FROM IO_TYPE WHERE Name = 'SDI')
INSERT INTO IO_TYPE (Name) SELECT 'SDO' WHERE NOT EXISTS (SELECT 1 FROM IO_TYPE WHERE Name = 'SDO')
INSERT INTO IO_TYPE (Name) SELECT 'SAI' WHERE NOT EXISTS (SELECT 1 FROM IO_TYPE WHERE Name = 'SAI')
INSERT INTO IO_TYPE (Name) SELECT 'SAO' WHERE NOT EXISTS (SELECT 1 FROM IO_TYPE WHERE Name = 'SAO')

-- Insert sample data into SIGNAL_TYPE
INSERT INTO SIGNAL_TYPE (Name) SELECT 'NC' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'NC')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'NO' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'NO')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'NC, 230V Relay' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'NC, 230V Relay')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'NO, 230V Relay' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'NO, 230V Relay')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'Int' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'Int')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'Real' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'Real')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'Float' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'Float')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'Word' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'Word')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'Double' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'Double')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'U_B_AnalogValueLong' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'U_B_AnalogValueLong')
INSERT INTO SIGNAL_TYPE (Name) SELECT '4-20mA, 2W' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = '4-20mA, 2W')
INSERT INTO SIGNAL_TYPE (Name) SELECT '4-20mA, 3W' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = '4-20mA, 3W')
INSERT INTO SIGNAL_TYPE (Name) SELECT '4-20mA, 4W' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = '4-20mA, 4W')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'PT100, 3W' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'PT100, 3W')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'PT100, 4W' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'PT100, 4W')
INSERT INTO SIGNAL_TYPE (Name) SELECT 'TC' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = 'TC')
INSERT INTO SIGNAL_TYPE (Name) SELECT '0-10V' WHERE NOT EXISTS (SELECT 1 FROM SIGNAL_TYPE WHERE Name = '0-10V')

-- Insert sample data into MODULE_TYPE
-- Insert sample data for "DI 8×24VDC ST"
INSERT INTO MODULE_TYPE (Name, OrderNumber, Channels, InBytes, InBits, OutBytes, OutBits, QIBytes) 
SELECT 'DI 8×24VDC ST', '6ES7131-6BF00-0BA0', 8, 1, 0, 0, 0, 1 
WHERE NOT EXISTS (SELECT 1 FROM MODULE_TYPE WHERE Name = 'DI 8×24VDC ST');

-- Insert sample data for "RQ 4×24VUC/2A CO ST"
INSERT INTO MODULE_TYPE (Name, OrderNumber, Channels, InBytes, InBits, OutBytes, OutBits, QIBytes)
SELECT 'RQ 4×24VUC/2A CO ST', '6ES7132-6GD50-0BA0', 4, 0, 0, 0, 4, 1
WHERE NOT EXISTS (SELECT 1 FROM MODULE_TYPE WHERE Name = 'RQ 4×24VUC/2A CO ST');

-- Insert sample data for "AI 4×I 2-/4-wire ST"
INSERT INTO MODULE_TYPE (Name, OrderNumber, Channels, InBytes, InBits, OutBytes, OutBits, QIBytes)
SELECT 'AI 4×I 2-/4-wire ST', '6ES7134-6GD00-0BA1', 4, 8, 0, 0, 0, 1
WHERE NOT EXISTS (SELECT 1 FROM MODULE_TYPE WHERE Name = 'AI 4×I 2-/4-wire ST');
-- Insert sample data for "AI 4×RTD/TC 2-/3-/4-wire HF"
INSERT INTO MODULE_TYPE (Name, OrderNumber, Channels, InBytes, InBits, OutBytes, OutBits, QIBytes)
SELECT 'AI 4×RTD/TC 2-/3-/4-wire HF', '6ES7134-6JD00-0CA1', 4, 8, 0, 0, 0, 1
WHERE NOT EXISTS (SELECT 1 FROM MODULE_TYPE WHERE Name = 'AI 4×RTD/TC 2-/3-/4-wire HF');

-- Insert sample data for "AI 4xU/I 2-wire ST"
INSERT INTO MODULE_TYPE (Name, OrderNumber, Channels, InBytes, InBits, OutBytes, OutBits, QIBytes)
SELECT 'AI 4xU/I 2-wire ST', '6ES7134-6HD00-0BA1', 4, 8, 0, 0, 0, 1
WHERE NOT EXISTS (SELECT 1 FROM MODULE_TYPE WHERE Name = 'AI 4xU/I 2-wire ST');

-- Insert sample data for "AQ 4×U/I ST"
INSERT INTO MODULE_TYPE (Name, OrderNumber, Channels, InBytes, InBits, OutBytes, OutBits, QIBytes)
SELECT 'AQ 4×U/I ST', '6ES7135-6HD00-0BA1', 4, 0, 0, 8, 0, 1
WHERE NOT EXISTS (SELECT 1 FROM MODULE_TYPE WHERE Name = 'AQ 4×U/I ST');

-- Insert sample data for "TM Count 1x24V"
INSERT INTO MODULE_TYPE (Name, OrderNumber, Channels, InBytes, InBits, OutBytes, OutBits, QIBytes)
SELECT 'TM Count 1x24V', '6ES7138-6AA00-0BA0', 1, 16, 0, 12, 0, 0
WHERE NOT EXISTS (SELECT 1 FROM MODULE_TYPE WHERE Name = 'TM Count 1x24V');

-- Insert sample data for "CM PtP communication module"
INSERT INTO MODULE_TYPE (Name, OrderNumber, Channels, InBytes, InBits, OutBytes, OutBits, QIBytes)
SELECT 'CM PtP communication module', '6ES7137-6AA00-0BA0', 1, 8, 0, 0, 0, 0
WHERE NOT EXISTS (SELECT 1 FROM MODULE_TYPE WHERE Name = 'CM PtP communication module');

-- Insert sample data into MODULE_CONFIG
INSERT INTO MODULE_CONFIG (IoTypeId, SignalTypeId, ModuleTypeId)
SELECT
    (SELECT Id FROM IO_TYPE WHERE Name = 'DI'),
    (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'),
    (SELECT Id FROM MODULE_TYPE WHERE Name = 'DI 8×24VDC ST')
WHERE NOT EXISTS (
    SELECT 1 FROM MODULE_CONFIG
    WHERE
        IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DI')
        AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO')
        AND ModuleTypeId = (SELECT Id FROM MODULE_TYPE WHERE Name = 'DI 8×24VDC ST')
);

INSERT INTO MODULE_CONFIG (IoTypeId, SignalTypeId, ModuleTypeId)
SELECT
    (SELECT Id FROM IO_TYPE WHERE Name = 'DI'),
    (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'),
    (SELECT Id FROM MODULE_TYPE WHERE Name = 'DI 8×24VDC ST')
WHERE NOT EXISTS (
    SELECT 1 FROM MODULE_CONFIG
    WHERE
        IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DI')
        AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC')
        AND ModuleTypeId = (SELECT Id FROM MODULE_TYPE WHERE Name = 'DI 8×24VDC ST')
);

INSERT INTO MODULE_CONFIG (IoTypeId, SignalTypeId, ModuleTypeId)
SELECT
    (SELECT Id FROM IO_TYPE WHERE Name = 'DO'),
    (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'),
    (SELECT Id FROM MODULE_TYPE WHERE Name = 'RQ 4×24VUC/2A CO ST')
WHERE NOT EXISTS (
    SELECT 1 FROM MODULE_CONFIG
    WHERE
        IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DO')
        AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO')
        AND ModuleTypeId = (SELECT Id FROM MODULE_TYPE WHERE Name = 'RQ 4×24VUC/2A CO ST')
);

INSERT INTO MODULE_CONFIG (IoTypeId, SignalTypeId, ModuleTypeId)
SELECT
    (SELECT Id FROM IO_TYPE WHERE Name = 'DO'),
    (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'),
    (SELECT Id FROM MODULE_TYPE WHERE Name = 'RQ 4×24VUC/2A CO ST')
WHERE NOT EXISTS (
    SELECT 1 FROM MODULE_CONFIG
    WHERE
        IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DO')
        AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC')
        AND ModuleTypeId = (SELECT Id FROM MODULE_TYPE WHERE Name = 'RQ 4×24VUC/2A CO ST')
);

INSERT INTO MODULE_CONFIG (IoTypeId, SignalTypeId, ModuleTypeId)
SELECT
    (SELECT Id FROM IO_TYPE WHERE Name = 'DO'),
    (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC, 230V Relay'),
    (SELECT Id FROM MODULE_TYPE WHERE Name = 'RQ 4×24VUC/2A CO ST')
WHERE NOT EXISTS (
    SELECT 1 FROM MODULE_CONFIG
    WHERE
        IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DO')
        AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC, 230V Relay')
        AND ModuleTypeId = (SELECT Id FROM MODULE_TYPE WHERE Name = 'RQ 4×24VUC/2A CO ST')
);

INSERT INTO MODULE_CONFIG (IoTypeId, SignalTypeId, ModuleTypeId)
SELECT
    (SELECT Id FROM IO_TYPE WHERE Name = 'DO'),
    (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO, 230V Relay'),
    (SELECT Id FROM MODULE_TYPE WHERE Name = 'RQ 4×24VUC/2A CO ST')
WHERE NOT EXISTS (
    SELECT 1 FROM MODULE_CONFIG
    WHERE
        IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DO')
        AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO, 230V Relay')
        AND ModuleTypeId = (SELECT Id FROM MODULE_TYPE WHERE Name = 'RQ 4×24VUC/2A CO ST')
);

INSERT INTO MODULE_CONFIG (IoTypeId, SignalTypeId, ModuleTypeId)
SELECT
    (SELECT Id FROM IO_TYPE WHERE Name = 'AI'),
    (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 2W'),
    (SELECT Id FROM MODULE_TYPE WHERE Name = 'AI 4×I 2-/4-wire ST')
WHERE NOT EXISTS (
    SELECT 1 FROM MODULE_CONFIG
    WHERE
        IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI')
        AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 2W')
        AND ModuleTypeId = (SELECT Id FROM MODULE_TYPE WHERE Name = 'AI 4×I 2-/4-wire ST')
);

INSERT INTO MODULE_CONFIG (IoTypeId, SignalTypeId, ModuleTypeId)
SELECT
    (SELECT Id FROM IO_TYPE WHERE Name = 'AI'),
    (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 4W'),
    (SELECT Id FROM MODULE_TYPE WHERE Name = 'AI 4×I 2-/4-wire ST')
WHERE NOT EXISTS (
    SELECT 1 FROM MODULE_CONFIG
    WHERE
        IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI')
        AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 4W')
        AND ModuleTypeId = (SELECT Id FROM MODULE_TYPE WHERE Name = 'AI 4×I 2-/4-wire ST')
);

INSERT INTO MODULE_CONFIG (IoTypeId, SignalTypeId, ModuleTypeId)
SELECT
    (SELECT Id FROM IO_TYPE WHERE Name = 'AI'),
    (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'PT100, 2W'),
    (SELECT Id FROM MODULE_TYPE WHERE Name = 'AI 4×RTD/TC 2-/3-/4-wire HF')
WHERE NOT EXISTS (
    SELECT 1 FROM MODULE_CONFIG
    WHERE
        IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI')
        AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'PT100, 2W')
        AND ModuleTypeId = (SELECT Id FROM MODULE_TYPE WHERE Name = 'AI 4×RTD/TC 2-/3-/4-wire HF')
);

INSERT INTO MODULE_CONFIG (IoTypeId, SignalTypeId, ModuleTypeId)
SELECT
    (SELECT Id FROM IO_TYPE WHERE Name = 'AI'),
    (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'PT100, 3W'),
    (SELECT Id FROM MODULE_TYPE WHERE Name = 'AI 4×RTD/TC 2-/3-/4-wire HF')
WHERE NOT EXISTS (
    SELECT 1 FROM MODULE_CONFIG
    WHERE
        IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI')
        AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'PT100, 3W')
        AND ModuleTypeId = (SELECT Id FROM MODULE_TYPE WHERE Name = 'AI 4×RTD/TC 2-/3-/4-wire HF')
);

INSERT INTO MODULE_CONFIG (IoTypeId, SignalTypeId, ModuleTypeId)
SELECT
    (SELECT Id FROM IO_TYPE WHERE Name = 'AI'),
    (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'PT100, 4W'),
    (SELECT Id FROM MODULE_TYPE WHERE Name = 'AI 4×RTD/TC 2-/3-/4-wire HF')
WHERE NOT EXISTS (
    SELECT 1 FROM MODULE_CONFIG
    WHERE
        IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI')
        AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'PT100, 4W')
        AND ModuleTypeId = (SELECT Id FROM MODULE_TYPE WHERE Name = 'AI 4×RTD/TC 2-/3-/4-wire HF')
);

INSERT INTO MODULE_CONFIG (IoTypeId, SignalTypeId, ModuleTypeId)
SELECT
    (SELECT Id FROM IO_TYPE WHERE Name = 'AI'),
    (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'TC'),
    (SELECT Id FROM MODULE_TYPE WHERE Name = 'AI 4×RTD/TC 2-/3-/4-wire HF')
WHERE NOT EXISTS (
    SELECT 1 FROM MODULE_CONFIG
    WHERE
        IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI')
        AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'TC')
        AND ModuleTypeId = (SELECT Id FROM MODULE_TYPE WHERE Name = 'AI 4×RTD/TC 2-/3-/4-wire HF')
);

INSERT INTO MODULE_CONFIG (IoTypeId, SignalTypeId, ModuleTypeId)
SELECT
    (SELECT Id FROM IO_TYPE WHERE Name = 'AI'),
    (SELECT Id FROM SIGNAL_TYPE WHERE Name = '0-10V'),
    (SELECT Id FROM MODULE_TYPE WHERE Name = 'AI 4xU/I 2-wire ST')
WHERE NOT EXISTS (
    SELECT 1 FROM MODULE_CONFIG
    WHERE
        IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI')
        AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = '0-10V')
        AND ModuleTypeId = (SELECT Id FROM MODULE_TYPE WHERE Name = 'AI 4xU/I 2-wire ST')
);

INSERT INTO MODULE_CONFIG (IoTypeId, SignalTypeId, ModuleTypeId)
SELECT
    (SELECT Id FROM IO_TYPE WHERE Name = 'AO'),
    (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 2W'),
    (SELECT Id FROM MODULE_TYPE WHERE Name = 'AQ 4×U/I ST')
WHERE NOT EXISTS (
    SELECT 1 FROM MODULE_CONFIG
    WHERE
        IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AO')
        AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 2W')
        AND ModuleTypeId = (SELECT Id FROM MODULE_TYPE WHERE Name = 'AQ 4×U/I ST')
);

INSERT INTO MODULE_CONFIG (IoTypeId, SignalTypeId, ModuleTypeId)
SELECT
    (SELECT Id FROM IO_TYPE WHERE Name = 'AO'),
    (SELECT Id FROM SIGNAL_TYPE WHERE Name = '0-10V'),
    (SELECT Id FROM MODULE_TYPE WHERE Name = 'AQ 4×U/I ST')
WHERE NOT EXISTS (
    SELECT 1 FROM MODULE_CONFIG
    WHERE
        IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AO')
        AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = '0-10V')
        AND ModuleTypeId = (SELECT Id FROM MODULE_TYPE WHERE Name = 'AQ 4×U/I ST')
);

-- Insert connections into IO_SIGNAL_TYPE
-- DI
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'DI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'DI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'));

-- DO
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'DO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'DO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC, 230V Relay'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'DO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC, 230V Relay'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'DO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO, 230V Relay'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'DO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO, 230V Relay'));

-- SDI
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SDI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SDI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SDI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SDI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'));

-- SDO
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SDO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SDO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SDO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SDO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'));

-- AI
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 2W'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'AI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 2W'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 4W'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'AI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 4W'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'PT100, 3W'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'AI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'PT100, 3W'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'PT100, 4W'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'AI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'PT100, 4W'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'TC'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'AI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'TC'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = '0-10V'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'AI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = '0-10V'));

--AO
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 2W'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'AO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = '4-20mA, 2W'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'AO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = '0-10V'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'AO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = '0-10V'));

-- SAI
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Int'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Int'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Real'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Real'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Float'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Float'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Word'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Word'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Double'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Double'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAI') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'U_B_AnalogValueLong'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'U_B_AnalogValueLong'));

-- SAO
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Int'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Int'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Real'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Real'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Float'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Float'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Word'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Word'));
IF NOT EXISTS (SELECT 1 FROM IO_SIGNAL_TYPE WHERE IoTypeId = (SELECT Id FROM IO_TYPE WHERE Name = 'SAO') AND SignalTypeId = (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Double'))
    INSERT INTO IO_SIGNAL_TYPE (IoTypeId, SignalTypeId) VALUES ((SELECT Id FROM IO_TYPE WHERE Name = 'SAO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'Double'));

-- Insert sample data into SYMBOL
INSERT INTO SYMBOL (Name) SELECT 'FI' WHERE NOT EXISTS (SELECT 1 FROM HIERARCHY_1 WHERE Name = 'FI')
INSERT INTO SYMBOL (Name) SELECT 'LAH' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='LAH')
INSERT INTO SYMBOL (Name) SELECT 'LAL' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='LAL')
INSERT INTO SYMBOL (Name) SELECT 'LI' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='LI')
INSERT INTO SYMBOL (Name) SELECT 'LIAL' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='LIAL')
INSERT INTO SYMBOL (Name) SELECT 'PAL' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='PAL')
INSERT INTO SYMBOL (Name) SELECT 'PI' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='PI')
INSERT INTO SYMBOL (Name) SELECT 'PIAL' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='PIAL')
INSERT INTO SYMBOL (Name) SELECT 'PTL' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='PTL')
INSERT INTO SYMBOL (Name) SELECT 'QI' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='QI')
INSERT INTO SYMBOL (Name) SELECT 'SAH' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='SAH')
INSERT INTO SYMBOL (Name) SELECT 'SI' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='SI')
INSERT INTO SYMBOL (Name) SELECT 'TI' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='TI')
INSERT INTO SYMBOL (Name) SELECT 'TIAH' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='TIAH')
INSERT INTO SYMBOL (Name) SELECT 'XA' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='XA')
INSERT INTO SYMBOL (Name) SELECT 'XC' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='XC')
INSERT INTO SYMBOL (Name) SELECT 'XI' WHERE NOT EXISTS (SELECT 1 FROM SYMBOL WHERE Name ='XI')

-- Insert sample data into ENG_UNIT if not already exists
IF NOT EXISTS (SELECT 1 FROM ENG_UNIT WHERE Name = 'V' AND UnitId = 1000)
    INSERT INTO ENG_UNIT (Name, UnitId) VALUES ('V', 1000);
IF NOT EXISTS (SELECT 1 FROM ENG_UNIT WHERE Name = 'deg C' AND UnitId = 1001)
    INSERT INTO ENG_UNIT (Name, UnitId) VALUES ('deg C', 1001);
IF NOT EXISTS (SELECT 1 FROM ENG_UNIT WHERE Name = 'bar' AND UnitId = 1002)
    INSERT INTO ENG_UNIT (Name, UnitId) VALUES ('bar', 1002);
IF NOT EXISTS (SELECT 1 FROM ENG_UNIT WHERE Name = 'rpm' AND UnitId = 1003)
    INSERT INTO ENG_UNIT (Name, UnitId) VALUES ('rpm', 1003);
IF NOT EXISTS (SELECT 1 FROM ENG_UNIT WHERE Name = '%' AND UnitId = 1004)
    INSERT INTO ENG_UNIT (Name, UnitId) VALUES ('%', 1004);

-- Insert sample data into OBJECT_TYPE
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Digital sensor' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_1DI'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Digital sensor', (SELECT Id FROM OTD WHERE Name = 'BO_1DI'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Fire detector' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_8DI_8DO'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Fire detector', (SELECT Id FROM OTD WHERE Name = 'BO_8DI_8DO'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Fire detector with commands' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_8DI_8DO'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Fire detector with commands', (SELECT Id FROM OTD WHERE Name = 'BO_8DI_8DO'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Multi DI/DO Object' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_8DI_8DO'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Multi DI/DO Object', (SELECT Id FROM OTD WHERE Name = 'BO_8DI_8DO'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Analog sensor' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_AnalogIn'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Analog sensor', (SELECT Id FROM OTD WHERE Name = 'BO_AnalogIn'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Analog sensor with alarms' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_AnalogIn'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Analog sensor with alarms', (SELECT Id FROM OTD WHERE Name = 'BO_AnalogIn'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Analog actuator' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_AnalogOut'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Analog actuator', (SELECT Id FROM OTD WHERE Name = 'BO_AnalogOut'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Breaker' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_Breaker'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Breaker', (SELECT Id FROM OTD WHERE Name = 'BO_Breaker'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Breaker feedback only' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_Breaker'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Breaker feedback only', (SELECT Id FROM OTD WHERE Name = 'BO_Breaker'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Duty Standby' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_DutyStby'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Duty Standby', (SELECT Id FROM OTD WHERE Name = 'BO_DutyStby'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Motor' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_Motor'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Motor', (SELECT Id FROM OTD WHERE Name = 'BO_Motor'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Motor feedback only' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_Motor'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Motor feedback only', (SELECT Id FROM OTD WHERE Name = 'BO_Motor'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Motor with VFD' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_MotorFC'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Motor with VFD', (SELECT Id FROM OTD WHERE Name = 'BO_MotorFC'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'PID controller' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_PID'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('PID controller', (SELECT Id FROM OTD WHERE Name = 'BO_PID'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Valve feedback only' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_Valve'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Valve feedback only', (SELECT Id FROM OTD WHERE Name = 'BO_Valve'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Valve' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_Valve'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Valve', (SELECT Id FROM OTD WHERE Name = 'BO_Valve'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Valve analog' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_ValveAI_AO'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Valve analog', (SELECT Id FROM OTD WHERE Name = 'BO_ValveAI_AO'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Tank' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_Tank'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Tank', (SELECT Id FROM OTD WHERE Name = 'BO_Tank'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Two Sensor selector' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_TwoSensors'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Two Sensor selector', (SELECT Id FROM OTD WHERE Name = 'BO_TwoSensors'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'Network Monitor' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'BO_NetworkMonitor'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('Network Monitor', (SELECT Id FROM OTD WHERE Name = 'BO_NetworkMonitor'));
IF NOT EXISTS (SELECT 1 FROM OBJECT_TYPE WHERE Name = 'NA' AND OtdId = (SELECT Id FROM OTD WHERE Name = 'NA'))
    INSERT INTO OBJECT_TYPE (Name, OtdId) VALUES ('NA', (SELECT Id FROM OTD WHERE Name = 'NA'));

--
-- Retrieve Ids for "Digital sensor"
DECLARE @DigitalSensorId INT;
SET @DigitalSensorId = (SELECT Id FROM OBJECT_TYPE WHERE Name = 'Digital sensor');

-- Insert "Digital sensor" data if not already exists
IF NOT EXISTS (SELECT 1 FROM TAG WHERE ObjectTypeId = @DigitalSensorId AND EqSuffix = '01')
    INSERT INTO TAG (ObjectTypeId, EqSuffix, Description, IoTypeId, SignalTypeId)
    VALUES (@DigitalSensorId, '01', 'Alarm', (SELECT Id FROM IO_TYPE WHERE Name = 'DI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NO'));

-- Retrieve Ids for "Fire detector"
DECLARE @FireDetectorId INT;
SET @FireDetectorId = (SELECT Id FROM OBJECT_TYPE WHERE Name = 'Fire detector');

-- Insert subcategories under "Fire detector" if not already exists
IF NOT EXISTS (SELECT 1 FROM TAG WHERE ObjectTypeId = @FireDetectorId AND EqSuffix = '01')
    INSERT INTO TAG (ObjectTypeId, EqSuffix, Description, IoTypeId, SignalTypeId)
    VALUES (@FireDetectorId, '01', 'Alarm', (SELECT Id FROM IO_TYPE WHERE Name = 'SDI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM TAG WHERE ObjectTypeId = @FireDetectorId AND EqSuffix = '02')
    INSERT INTO TAG (ObjectTypeId, EqSuffix, Description, IoTypeId, SignalTypeId)
    VALUES (@FireDetectorId, '02', 'Warning', (SELECT Id FROM IO_TYPE WHERE Name = 'SDI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM TAG WHERE ObjectTypeId = @FireDetectorId AND EqSuffix = '03')
    INSERT INTO TAG (ObjectTypeId, EqSuffix, Description, IoTypeId, SignalTypeId)
    VALUES (@FireDetectorId, '03', 'Fault', (SELECT Id FROM IO_TYPE WHERE Name = 'SDI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM TAG WHERE ObjectTypeId = @FireDetectorId AND EqSuffix = '04')
    INSERT INTO TAG (ObjectTypeId, EqSuffix, Description, IoTypeId, SignalTypeId)
    VALUES (@FireDetectorId, '04', 'Disabled', (SELECT Id FROM IO_TYPE WHERE Name = 'SDI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM TAG WHERE ObjectTypeId = @FireDetectorId AND EqSuffix = '04')
    INSERT INTO TAG (ObjectTypeId, EqSuffix, Description, IoTypeId, SignalTypeId)
    VALUES (@FireDetectorId, '05', 'Test', (SELECT Id FROM IO_TYPE WHERE Name = 'SDI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));

-- Retrieve Ids for "Fire detector with commands"
DECLARE @FireDetectorWithCommandsId INT;
SET @FireDetectorWithCommandsId = (SELECT Id FROM OBJECT_TYPE WHERE Name = 'Fire detector with commands');

-- Insert subcategories under "Fire detector with commands" if not already exists
IF NOT EXISTS (SELECT 1 FROM TAG WHERE ObjectTypeId = @FireDetectorWithCommandsId AND EqSuffix = '01')
    INSERT INTO TAG (ObjectTypeId, EqSuffix, Description, IoTypeId, SignalTypeId)
    VALUES (@FireDetectorWithCommandsId, '01', 'Alarm', (SELECT Id FROM IO_TYPE WHERE Name = 'SDI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM TAG WHERE ObjectTypeId = @FireDetectorWithCommandsId AND EqSuffix = '02')
    INSERT INTO TAG (ObjectTypeId, EqSuffix, Description, IoTypeId, SignalTypeId)
    VALUES (@FireDetectorWithCommandsId, '02', 'Warning', (SELECT Id FROM IO_TYPE WHERE Name = 'SDI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM TAG WHERE ObjectTypeId = @FireDetectorWithCommandsId AND EqSuffix = '03')
    INSERT INTO TAG (ObjectTypeId, EqSuffix, Description, IoTypeId, SignalTypeId)
    VALUES (@FireDetectorWithCommandsId, '03', 'Fault', (SELECT Id FROM IO_TYPE WHERE Name = 'SDI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM TAG WHERE ObjectTypeId = @FireDetectorWithCommandsId AND EqSuffix = '04')
    INSERT INTO TAG (ObjectTypeId, EqSuffix, Description, IoTypeId, SignalTypeId)
    VALUES (@FireDetectorWithCommandsId, '04', 'Disabled', (SELECT Id FROM IO_TYPE WHERE Name = 'SDI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM TAG WHERE ObjectTypeId = @FireDetectorWithCommandsId AND EqSuffix = '05')
    INSERT INTO TAG (ObjectTypeId, EqSuffix, Description, IoTypeId, SignalTypeId)
    VALUES (@FireDetectorWithCommandsId, '05', 'Test', (SELECT Id FROM IO_TYPE WHERE Name = 'SDI'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM TAG WHERE ObjectTypeId = @FireDetectorWithCommandsId AND EqSuffix = '21')
    INSERT INTO TAG (ObjectTypeId, EqSuffix, Description, IoTypeId, SignalTypeId)
    VALUES (@FireDetectorWithCommandsId, '21', 'Disable', (SELECT Id FROM IO_TYPE WHERE Name = 'SDO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));
IF NOT EXISTS (SELECT 1 FROM TAG WHERE ObjectTypeId = @FireDetectorWithCommandsId AND EqSuffix = '22')
    INSERT INTO TAG (ObjectTypeId, EqSuffix, Description, IoTypeId, SignalTypeId)
    VALUES (@FireDetectorWithCommandsId, '22', 'Enable', (SELECT Id FROM IO_TYPE WHERE Name = 'SDO'), (SELECT Id FROM SIGNAL_TYPE WHERE Name = 'NC'));